version: '3'
services:
  front:
    image: contacts.client
    build: contact-spa
    ports:
      - '4200:4200'
    links:
      - back
  back:
    image: contacts.backend
    build: contact-api
    command: npm start
    ports:
      - '3000:3000'
    links:
      - db
  db:
    image: mongo
    ports:
      - '27017:27017'
    restart: always